name: JoinPlugin
version: ${project.version}
main: me.hyperburger.joinplugin.JoinPlugin
api-version: 1.13
authors: [ HyperBurger ]
description: A Custom Coded Join Plugin
commands:
  JoinPlugin:
    description: JoinPlugin Main Command
    aliases:
      - jp
      - joinp